Repository dnd-side-project/dnd-11th-7-frontend, pull requests merged in 2024-09, with the labels that each got.

#112 [FEAT] Card 컴포넌트, 스토리북
  src/assets/icons/index.tsx
  src/assets/icons/jjakkak-body.svg
  src/assets/icons/jjakkak-hands.svg
  src/components/features/Card/Card.stories.tsx
  src/components/features/Card/Card.styled.ts
  src/components/features/Card/Card.types.ts
  src/components/features/Card/index.tsx
Labels: feat

#117 [FEAT] Chip 버라이언트 및 스크롤 그룹 추가
  src/components/common/Chip/Chip.stories.tsx
  src/components/common/Chip/Chip.styled.ts
  src/components/common/Chip/Chip.types.ts
  src/components/common/Chip/index.tsx
  src/components/common/FormLayout/index.tsx
  src/components/common/Header/Header.stories.tsx
  src/components/features/CreateMeetingForm/CategoryForm.tsx
  src/styles/global.ts
Labels: feat

#124 [FEAT] Icon 추가
  src/assets/icons/index.tsx
  src/assets/icons/next.svg
  src/assets/icons/plus.svg
  src/assets/icons/prev.svg
  src/components/common/Icon/Icon.stories.tsx
  src/components/common/Icon/Icon.types.ts
  src/components/common/Icon/index.tsx
Labels: feat

#114 [FEAT] MemberCard 컴포넌트, 스토리북 구현
  src/components/features/MemberCard/MemberCard.stories.tsx
  src/components/features/MemberCard/MemberCard.styled.ts
  src/components/features/MemberCard/MemberCard.types.ts
  src/components/features/MemberCard/index.tsx
Labels: feat

#127 [FEAT] 말풍선 컴포넌트, 스토리북
  src/components/common/SpeechBubble/SpeechBubble.stories.tsx
  src/components/common/SpeechBubble/SpeechBubble.styled.ts
  src/components/common/SpeechBubble/SpeechBubble.types.ts
  src/components/common/SpeechBubble/index.tsx
Labels: feat

#110 [FEAT] 모임 생성 폼 상태 정리
  src/components/features/CreateMeetingForm/AnonymousForm.tsx
  src/components/features/CreateMeetingForm/CategoryForm.tsx
  src/components/features/CreateMeetingForm/CreateMeetingForm.stories.tsx
  src/components/features/CreateMeetingForm/DueDateForm.tsx
  src/components/features/CreateMeetingForm/MeetingDateRangeForm.tsx
  src/components/features/CreateMeetingForm/MeetingNameForm.tsx
  src/components/features/CreateMeetingForm/MemberCountForm.tsx
  src/components/features/CreateMeetingForm/types.ts
  src/constants/meetingForm.ts
  src/hooks/useFunnel.tsx
  src/hooks/useMeetingFormState.tsx
  src/pages/NewMeeting.tsx
  src/types/meeting.ts
Labels: feat

#133 [REFACTOR] Calendar 지난 날짜 dim처리
  src/components/common/Calendar/Calendar.styled.ts
  src/components/common/Calendar/Calendar.types.ts
  src/components/common/Calendar/index.tsx
  src/hooks/useCalendar.tsx
Labels: refactor

#131 [FEAT] ScheduleCard 스토리북, 컴포넌트 구현
  src/components/common/Card/Card.stories.tsx
  src/components/common/Card/Card.styled.ts
  src/components/common/Card/Card.types.ts
  src/components/common/Card/index.tsx
  src/components/common/Chip/Chip.styled.ts
  src/components/features/ScheduleCard/ScheduleCard.stories.tsx
  src/components/features/ScheduleCard/ScheduleCard.styled.ts
  src/components/features/ScheduleCard/ScheduleCard.types.ts
  src/components/features/ScheduleCard/index.tsx
Labels: feat

#129 [FEAT] 로그인 기능 구현
  src/apis/.gitkeep
  src/apis/index.ts
  src/apis/member/api.ts
  src/apis/member/queries.ts
  src/apis/member/type.ts
  src/components/features/KakaoLoginButton/KakaoLoginButton.styled.ts
  src/components/features/KakaoLoginButton/index.tsx
  src/constants/endpoint.ts
  src/hooks/useAuth.tsx
  src/lib/axios.ts
  src/main.tsx
  src/pages/Login.tsx
  src/pages/LoginFailure.tsx
  src/pages/LoginSuccess.tsx
  src/routes/PrivateRoute.tsx
  src/routes/route.tsx
Labels: feat

#135 [FEAT] Border 컴포넌트, 스토리북
  src/components/common/Border/Border.stories.tsx
  src/components/common/Border/Border.styled.ts
  src/components/common/Border/Border.types.ts
  src/components/common/Border/index.tsx
Labels: feat

#139 [FEAT] 퍼널 스텝에서 마지막(summary) 페이지 제외
  src/components/features/CreateMeetingForm/AnonymousForm.tsx
  src/components/features/CreateMeetingForm/CategoryForm.tsx
  src/components/features/CreateMeetingForm/DueDateForm.tsx
  src/components/features/CreateMeetingForm/MeetingDateRangeForm.tsx
  src/components/features/CreateMeetingForm/MeetingNameForm.tsx
  src/components/features/CreateMeetingForm/MemberCountForm.tsx
  src/hooks/useMeetingFormProgressContext.tsx
Labels: feat

#128 [FEAT] ScheduleInput 컴포넌트, 스토리북
  src/components/common/ScheduleInput/ScheduleInput.stories.tsx
  src/components/common/ScheduleInput/ScheduleInput.styled.ts
  src/components/common/ScheduleInput/ScheduleInput.type.ts
  src/components/common/ScheduleInput/index.tsx
  src/components/common/TimeRangePicker/TimeRangePicker.stories.tsx
  src/components/common/TimeRangePicker/TimeRangePicker.styled.ts
  src/components/common/TimeRangePicker/TimeRangePicker.type.ts
  src/components/common/TimeRangePicker/index.tsx
  src/hooks/useSchedule.tsx
  src/utils/formatTime.ts
  src/utils/parseTimeRanges.ts
Labels: feat

#140 [FEAT] 일정 마감 기한 선택지 조건부 노출
  src/components/features/CreateMeetingForm/DueDateForm.tsx
  src/components/features/CreateMeetingForm/types.ts
  src/pages/NewMeeting.tsx
Labels: feat

#141 [FEAT] 모임 생성 api 함수와 관련 아이콘 에셋 추가
  src/apis/index.ts
  src/apis/meeting/api.ts
  src/apis/meeting/mutations.ts
  src/apis/meeting/type.ts
  src/assets/icons/index.tsx
  src/assets/icons/jjakkak-9-with-stage.svg
  src/constants/endpoint.ts
Labels: feat

#136 [REFACTOR] PinInput 모바일 UI 개선
  src/components/common/PinInput/PinInput.styled.tsx
  src/components/common/PinInput/index.tsx
  src/hooks/usePinInput.tsx
Labels: refactor

#146 [FEAT] 헤더 UI 개선
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/Header.styled.ts
  src/components/common/Header/index.tsx
Labels: feat

#154 [BUGFIX] Slider 스토리북 수정
  src/components/common/Slider/Slider.stories.tsx
  src/components/common/Slider/Slider.styled.ts
Labels: fix

#152 [BUGFIX] useSchedule getSelectedTimeRanges 배열 객체로 변환
  src/hooks/useSchedule.tsx
Labels: fix

#171 [FEAT] IconButton에 iconColor 프롭 추가
  src/components/common/IconButton/IconButton.stories.tsx
  src/components/common/IconButton/IconButton.types.ts
  src/components/common/IconButton/index.tsx
Labels: feat

#145 [FEAT] 모임 생성 api 연결
  src/components/features/CreateMeetingForm/CategoryForm.tsx
  src/components/features/CreateMeetingForm/CreateMeetingForm.stories.tsx
  src/components/features/CreateMeetingForm/Summary.tsx
  src/constants/meetingForm.ts
  src/main.tsx
  src/pages/NewMeeting.tsx
  src/pages/NewMeetingShare.tsx
  src/routes/route.tsx
Labels: feat

#159 [FEAT] FloatingActionButton 컴포넌트, 스토리북
  src/assets/icons/add.svg
  src/assets/icons/index.tsx
  src/components/common/AppLayout/AppLayout.styled.ts
  src/components/common/FloatingActionButton/FloatingActionButton.stories.tsx
  src/components/common/FloatingActionButton/FloatingActionButton.styled.ts
  src/components/common/FloatingActionButton/FloatingActionButton.types.ts
  src/components/common/FloatingActionButton/index.tsx
Labels: feat

#161 [FEAT] 모임 생성 폼에서 Slider의 Min 값 수정
  src/components/features/CreateMeetingForm/CreateMeetingForm.stories.tsx
  src/components/features/CreateMeetingForm/MemberCountForm.tsx
Labels: feat

#164 [ FIX] ScheduleInput border처리, IconButton 변경
  src/components/common/ScheduleInput/index.tsx
  src/components/common/TimeRangePicker/TimeRangePicker.styled.ts
Labels: fix

#172 [FEAT] ScheduleLayout 스토리북, 컴포넌트 구현
  src/components/common/ScheduleLayout/ScheduleLayout.stories.tsx
  src/components/common/ScheduleLayout/ScheduleLayout.styled.ts
  src/components/common/ScheduleLayout/ScheduleLayout.types.ts
  src/components/common/ScheduleLayout/index.tsx
Labels: feat

#163 [FEAT] ScheduleForm 폼 로직 생성
  src/components/features/CreateScheduleForm/CreateScheduleForm.stories.tsx
  src/components/features/CreateScheduleForm/NickNameForm.tsx
  src/components/features/CreateScheduleForm/ScheduleInputForm.tsx
  src/components/features/CreateScheduleForm/types.ts
  src/constants/scheduleFrom.ts
  src/pages/NewSchedule.tsx
  src/types/.gitkeep
  src/types/schedule.ts
Labels: feat

#174 [BUGFIX] interceptor의 reissue 미동작 해결
  src/apis/member/api.ts
  src/lib/axios.ts
Labels: fix

#158 [FEAT] Chip에 primaryWeak 버라이언트 추가
  src/components/common/Chip/Chip.stories.tsx
  src/components/common/Chip/Chip.styled.ts
  src/components/common/Chip/Chip.types.ts
Labels: feat

#147 [FEAT] 온보딩 페이지 마크업, 액세스 로직
  src/assets/icons/index.tsx
  src/assets/icons/jjakkak-circle-1.svg
  src/assets/icons/jjakkak-circle-2.svg
  src/assets/icons/jjakkak-logo-1.svg
  src/assets/icons/jjakkak-logo-2.svg
  src/pages/Login.tsx
  src/pages/LoginFailure.tsx
  src/pages/LoginSuccess.tsx
  src/pages/Onboarding.tsx
  src/routes/route.tsx
Labels: feat

#177 [FEAT] 식별자 확인 페이지 구현
  src/pages/PinRelease.tsx
Labels: feat

#179 [FEAT] 일정 결과 전체조회 페이지 UI 작업
  src/pages/TotalSchedule.tsx
Labels: feat

#187 [BUGFIX] 스크롤 화면일 때 배경색 사라지지 않도록
  src/components/common/AppLayout/AppLayout.styled.ts
Labels: fix

#184 [BUGFIX] 헤더에 배경색 적용되도록
  src/components/common/Header/index.tsx
Labels: fix

#182 [FEAT] 모임 목록 페이지 UI
  src/components/features/MeetingList/MeetingList.stories.tsx
  src/components/features/MeetingList/index.tsx
  src/pages/Meeting.tsx
  src/routes/route.tsx
  src/types/meeting.ts
  src/utils/isPastDate.ts
Labels: feat

#185 [FEAT] 일정 수정 폼 로직 작성
  src/components/features/EditScheduleForm/EditScheduleForm.stories.tsx
  src/components/features/EditScheduleForm/EditScheduleInputForm.tsx
  src/components/features/EditScheduleForm/PinInputForm.tsx
  src/components/features/EditScheduleForm/types.ts
  src/pages/EditSchedule.tsx
Labels: feat

#191 [FEAT] ScheduleLayout Header backgroundColor 지정
  src/components/common/ScheduleLayout/ScheduleLayout.styled.ts
  src/components/common/ScheduleLayout/index.tsx
Labels: feat

#189 [FIX] FixedBottomButton css 수정
  src/components/common/FixedBottomButton/FixedBottomButton.styled.ts
Labels: fix

#200 [FEAT] MeetingDetail 페이지 UI
  src/components/features/MeetingDetail/MeetingDetail.stories.tsx
  src/components/features/MeetingDetail/index.tsx
  src/pages/MeetingDetail.tsx
  src/utils/formatDateTime.ts
Labels: feat

#216 [FEAT] color 추가
  src/styles/global.ts
Labels: feat

#217 [FEAT] Copy Icon 추가
  src/assets/icons/copy.svg
  src/assets/icons/index.tsx
Labels: feat

#218 [FEAT] ScheduleLayout background color 변경
  src/components/common/ScheduleLayout/ScheduleLayout.styled.ts
  src/components/common/ScheduleLayout/index.tsx
Labels: feat

#214 [FEAT] ScheduleInput/TimeRangePicker totalPeopleNum, meetingTimeList Props 추가
  src/components/common/ScheduleInput/ScheduleInput.type.ts
  src/components/common/ScheduleInput/index.tsx
  src/components/common/TimeRangePicker/TimeRangePicker.styled.ts
  src/components/common/TimeRangePicker/TimeRangePicker.type.ts
  src/components/common/TimeRangePicker/index.tsx
Labels: feat

#219 [FEAT] 식별자 페이지 UI 수정
  src/pages/PinRelease.tsx
Labels: feat

#206 [FEAT] MeetingDetail api 연결
  src/apis/index.ts
  src/apis/meeting/api.ts
  src/apis/meeting/queries.ts
  src/apis/meeting/type.ts
  src/components/common/ScheduleLayout/ScheduleLayout.stories.tsx
  src/components/common/ScheduleLayout/ScheduleLayout.styled.ts
  src/components/common/ScheduleLayout/ScheduleLayout.types.ts
  src/components/common/ScheduleLayout/index.tsx
  src/components/features/MeetingDetail/MeetingDetail.stories.tsx
  src/components/features/MeetingDetail/MeetingDetail.type.ts
  src/components/features/MeetingDetail/MeetingInfo.tsx
  src/components/features/MeetingDetail/MemberList.tsx
  src/components/features/MeetingDetail/MemberScheduleCard.tsx
  src/components/features/MeetingDetail/index.tsx
  src/pages/MeetingDetail.tsx
  src/routes/route.tsx
Labels: feat

#224 [FEAT] 일정 한눈에 보기 페이지 API 연결
  src/components/common/TimeRangePicker/TimeRangePicker.styled.ts
  src/components/common/TimeRangePicker/index.tsx
  src/components/features/MeetingDetail/MemberScheduleCard.tsx
  src/pages/TimeCollection.tsx
  src/routes/route.tsx
Labels: feat

#221 [FEAT] 일정 전체 조회 API 연결
  src/apis/meeting/api.ts
  src/apis/meeting/queries.ts
  src/components/features/TotalScheduleList/TotalScheduleList.tsx
  src/components/features/TotalScheduleList/TotalScheduleList.type.ts
  src/pages/TotalSchedule.tsx
Labels: feat

#222 [FEAT] 일정 POST API 연결
  src/apis/index.ts
  src/apis/schedule/api.ts
  src/apis/schedule/mutations.ts
  src/apis/schedule/type.ts
  src/components/features/CreateScheduleForm/CreateScheduleForm.stories.tsx
  src/components/features/CreateScheduleForm/NickNameForm.tsx
  src/components/features/CreateScheduleForm/ScheduleInputForm.tsx
  src/components/features/CreateScheduleForm/types.ts
  src/constants/auth.ts
  src/pages/EditSchedule.tsx
  src/pages/NewSchedule.tsx
  src/types/schedule.ts
Labels: feat

#229 [FEAT] 식별자 state 노출
  src/components/common/TimeRangePicker/TimeRangePicker.styled.ts
  src/pages/PinRelease.tsx
Labels: feat

#227 [FEAT] 일정 수정 API 연결
  src/apis/index.ts
  src/apis/schedule/api.ts
  src/apis/schedule/mutations.ts
  src/apis/schedule/queries.ts
  src/apis/schedule/type.ts
  src/components/common/TimeRangePicker/index.tsx
  src/components/features/CreateScheduleForm/ScheduleInputForm.tsx
  src/components/features/CreateScheduleForm/types.ts
  src/components/features/EditScheduleForm/EditScheduleContent.tsx
  src/components/features/EditScheduleForm/EditScheduleForm.stories.tsx
  src/components/features/EditScheduleForm/PinInputForm.tsx
  src/components/features/EditScheduleForm/types.ts
  src/components/features/TotalScheduleList/TotalScheduleList.tsx
  src/pages/EditSchedule.tsx
  src/pages/NewSchedule.tsx
  src/utils/formatTime.ts
Labels: feat
