Repository dnd-side-project/dnd-11th-7-frontend, pull requests merged in 2024-10, with the labels that each got.

#233 [FEAT] NotFound 페이지 구현
  src/assets/icons/index.tsx
  src/pages/NotFound.tsx
  src/routes/route.tsx
Labels: feat

#234 [FEAT] PinInput helper 추가
  src/components/common/PinInput/PinInput.types.tsx
  src/components/common/PinInput/index.tsx
  src/components/features/EditScheduleForm/EditScheduleContent.tsx
  src/components/features/EditScheduleForm/PinInputForm.tsx
  src/components/features/EditScheduleForm/types.ts
  src/pages/EditSchedule.tsx
Labels: feat

#236 [FEAT] 일정 입력/수정 시 Modal 내 navigate 수정
  src/components/common/Modal/index.tsx
  src/components/features/EditScheduleForm/EditScheduleContent.tsx
  src/components/features/EditScheduleForm/EditScheduleForm.stories.tsx
  src/constants/scheduleForm.ts
  src/pages/EditSchedule.tsx
  src/pages/NewSchedule.tsx
Labels: feat

#242 [FEAT] 회원 일정 작성 여부 조회 api 연결
  src/apis/meeting/api.ts
  src/apis/meeting/queries.ts
  src/components/features/MeetingDetail/MemberScheduleCard.tsx
  src/pages/MeetingDetail.tsx
Labels: feat

#243 [FEAT] MemberList에서 리더가 가장 처음에 위치하도록 수정
  src/components/features/MeetingDetail/MemberList.tsx
Labels: feat

#245 [BUGFIX] 일정 수정 시 변경된 일정이 저장이 안되는 버그
  src/hooks/useSchedule.tsx
Labels: fix

#232 [FEAT] 라우트 경로 정리
  src/lib/env.ts
  src/pages/Landing.tsx
  src/pages/Login.tsx
  src/pages/LoginSuccess.tsx
  src/pages/NewMeetingShare.tsx
  src/pages/Onboarding.tsx
  src/routes/PrivateRoute.tsx
  src/routes/RequireAuthRoute.tsx
  src/routes/route.tsx
  src/utils/regex.ts
Labels: feat

#246 [FEAT] 모임 일정 시간 조회 무한 스크롤 기능
  src/apis/meeting/api.ts
  src/apis/meeting/queries.ts
  src/apis/meeting/type.ts
  src/components/features/TotalScheduleList/TotalScheduleList.tsx
  src/components/features/TotalScheduleList/TotalScheduleList.type.ts
  src/pages/TimeCollection.tsx
  src/pages/TotalSchedule.tsx
Labels: feat

#248 [FEAT] Date YYYY. MM. DD 형식에 맞도록 수정
  src/components/features/MeetingDetail/MeetingInfo.tsx
  src/utils/formatDate.ts
Labels: feat

#250 [FEAT] favicon, title 설정
  index.html
  public/icons/jjakkak-logo.png
  public/icons/kakao_login.png
  src/pages/NewSchedule.tsx
Labels: feat

#251 [FEAT] Landing 페이지 UI
  public/images/landing1.png
  public/images/landing2.png
  public/images/landing3.png
  src/assets/icons/index.tsx
  src/assets/icons/jjakkaks-illust-2.svg
  src/components/common/LandingContentLayout/LandingContentLayout.types.ts
  src/components/common/LandingContentLayout/index.tsx
  src/pages/Landing.tsx
  src/pages/Login.tsx
Labels: feat

#252 [FEAT] 링크 공유 기능
  .pnp.cjs
  .yarn/cache/invariant-npm-2.2.4-717fbdb119-5af133a917.zip
  .yarn/cache/react-fast-compare-npm-3.2.2-45b585a872-0bbd2f3eb4.zip
  .yarn/cache/react-helmet-async-npm-2.0.5-f913a66ef6-f390ea8bf1.zip
  .yarn/cache/shallowequal-npm-1.1.0-6688d419cb-b926efb51c.zip
  index.html
  package.json
  public/images/kakao-share-thumbnail.png
  src/global.d.ts
  src/hooks/useKakaoSdk.tsx
  src/lib/env.ts
  src/main.tsx
  src/pages/MeetingDetail.tsx
  src/pages/NewMeetingShare.tsx
  src/utils/copy.ts
  tsconfig.json
  yarn.lock
Labels: feat

#258 [REFACTOR] 회원 일정 작성 여부 api path 변경
  src/apis/meeting/api.ts
  src/pages/NewMeetingShare.tsx
Labels: refactor

#263 [ FIX] 버튼 padding-bottom 수정
  src/components/common/FixedBottomButton/FixedBottomButton.styled.ts
  src/components/common/FormLayout/index.tsx
  src/components/common/ScheduleInput/ScheduleInput.styled.ts
  src/components/features/CreateScheduleForm/ScheduleInputForm.tsx
  src/components/features/EditScheduleForm/EditScheduleInputForm.tsx
  src/components/features/TotalScheduleList/TotalScheduleList.tsx
  src/pages/TimeCollection.tsx
  src/pages/TotalSchedule.tsx
Labels: fix

#264 [FEAT] 현재 진행 중인 모임을 가장 상단에 위치하도록 수정
  src/pages/Meeting.tsx
Labels: feat

#265 [FIX] FAB position 변경
  src/components/common/FloatingActionButton/FloatingActionButton.styled.ts
Labels: fix
