Repository dnd-side-project/dnd-11th-7-frontend, pull requests merged in 2024-08, with the labels that each got.

#13 [FEAT] global color palette, 스토리북
  src/styles/Color.mdx
  src/styles/global.ts
Labels: feat

#14 [FEAT] Typography 컴포넌트, 스토리북
  .storybook/preview.ts
  public/fonts/PretendardVariable.woff2
  src/components/common/Typography/Typography.mdx
  src/components/common/Typography/Typography.styled.ts
  src/components/common/Typography/index.tsx
  src/index.css
  src/styles/global.ts
Labels: feat

#16 [FEAT] FlexBox 컴포넌트, 스토리북
  src/components/common/FlexBox/FlexBox.stories.tsx
  src/components/common/FlexBox/FlexBox.styled.ts
  src/components/common/FlexBox/FlexBox.types.ts
  src/components/common/FlexBox/index.tsx
Labels: feat

#17 [FEAT] Button 컴포넌트, 스토리북
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.styled.ts
  src/components/common/Button/Button.types.ts
  src/components/common/Button/index.tsx
  src/styles/Color.mdx
  src/styles/global.ts
Labels: feat

#18 [FEAT] Chip 컴포넌트, 스토리북
  src/components/common/Chip/Chip.stories.tsx
  src/components/common/Chip/Chip.styled.ts
  src/components/common/Chip/Chip.types.ts
  src/components/common/Chip/index.tsx
Labels: feat

#22 [FEAT] Typography에 color 프롭 추가
  src/components/common/Typography/index.tsx
Labels: feat

#27 [FEAT] FlexBox에 margin, padding 프롭 추가
  src/components/common/FlexBox/FlexBox.stories.tsx
  src/components/common/FlexBox/FlexBox.styled.ts
  src/components/common/FlexBox/FlexBox.types.ts
Labels: feat

#28 [FEAT] Slider 컴포넌트
  src/components/common/Button/Button.styled.ts
  src/components/common/Button/index.tsx
  src/components/common/Slider/Slider.stories.tsx
  src/components/common/Slider/Slider.styled.ts
  src/components/common/Slider/Slider.types.ts
  src/components/common/Slider/index.tsx
Labels: feat

#24 [FEAT] TextField 컴포넌트, 스토리북
  .storybook/preview.ts
  public/icons/delete-rounded.svg
  src/components/common/TextField/TextField.stories.tsx
  src/components/common/TextField/TextField.styled.ts
  src/components/common/TextField/TextField.types.ts
  src/components/common/TextField/index.tsx
  src/index.css
  src/styles/global.ts
Labels: feat

#39 [FEAT] Icon 컴포넌트, 스토리북
  .pnp.cjs
  .storybook/main.ts
  .yarn/cache/@babel-compat-data-npm-7.25.2-119057710e-5bf1f14d6e.zip
  .yarn/cache/@babel-core-npm-7.25.2-341930f809-a425fa40e7.zip
  .yarn/cache/@babel-generator-npm-7.25.0-4bba208756-d0e2dfcdc8.zip
  .yarn/cache/@babel-helper-compilation-targets-npm-7.25.2-27e0232144-de10e986b5.zip
  .yarn/cache/@babel-helper-module-transforms-npm-7.25.2-2c8d511580-adaa15970a.zip
  .yarn/cache/@babel-helpers-npm-7.25.0-f552d9aaf3-b7fe007fc4.zip
  .yarn/cache/@babel-parser-npm-7.25.3-e33bb4a0e6-874b01349a.zip
  .yarn/cache/@babel-template-npm-7.25.0-2c6ddcb43a-4e31afd873.zip
  .yarn/cache/@babel-traverse-npm-7.25.3-69c3455e97-4c8a1966fa.zip
  .yarn/cache/@babel-types-npm-7.25.2-7d3fc0ed1e-e489435856.zip
  .yarn/cache/@svgr-babel-plugin-add-jsx-attribute-npm-8.0.0-026be9c2be-a50bd0baa3.zip
  .yarn/cache/@svgr-babel-plugin-remove-jsx-attribute-npm-8.0.0-c98774fd19-8a98e59bd9.zip
  .yarn/cache/@svgr-babel-plugin-remove-jsx-empty-expression-npm-8.0.0-bee2c7d451-517dcca752.zip
  .yarn/cache/@svgr-babel-plugin-replace-jsx-attribute-value-npm-8.0.0-bf8ed25593-004bd18920.zip
  .yarn/cache/@svgr-babel-plugin-svg-dynamic-title-npm-8.0.0-c534fda2ad-80e0a7fcf9.zip
  .yarn/cache/@svgr-babel-plugin-svg-em-dimensions-npm-8.0.0-de7e3b5c02-73e92c8277.zip
  .yarn/cache/@svgr-babel-plugin-transform-react-native-svg-npm-8.1.0-9f7491cf96-655ed6bc7a.zip
  .yarn/cache/@svgr-babel-plugin-transform-svg-component-npm-8.0.0-2e9be9c6ad-4ac00bb99a.zip
  .yarn/cache/@svgr-babel-preset-npm-8.1.0-0dca9b0e1b-49367d3ad0.zip
  .yarn/cache/@svgr-core-npm-8.1.0-77cc138b8f-6a2f6b1bc7.zip
  .yarn/cache/@svgr-hast-util-to-babel-ast-npm-8.0.0-5d74d59e64-f4165b583b.zip
  .yarn/cache/@svgr-plugin-jsx-npm-8.1.0-e2710753df-07b4d9e00d.zip
  .yarn/cache/camelcase-npm-6.3.0-e5e42a0d15-0d70165821.zip
  .yarn/cache/cosmiconfig-npm-8.3.6-a5566e2779-0382a9ed13.zip
  .yarn/cache/dot-case-npm-3.0.4-09675b5521-5b859ea650.zip
  .yarn/cache/entities-npm-4.5.0-7cdb83b832-5b039739f7.zip
  .yarn/cache/lower-case-npm-2.0.2-151055f1c2-3d925e0903.zip
  .yarn/cache/no-case-npm-3.0.4-12884c3d98-8ef545f0b3.zip
  .yarn/cache/snake-case-npm-3.0.4-67f447c30d-ab19a91396.zip
  .yarn/cache/svg-parser-npm-2.0.4-1b0b6afbe9-02f6cb155d.zip
  .yarn/cache/vite-plugin-svgr-npm-4.2.0-e0c6a7a1f0-0a6400f209.zip
  package.json
  public/.gitkeep
  src/assets/.gitkeep
  src/assets/icons/back.svg
  src/assets/icons/index.tsx
  src/assets/icons/kakaotalk.svg
  src/assets/icons/left.svg
  src/assets/icons/link.svg
  src/assets/icons/right.svg
  src/assets/icons/user.svg
  src/components/common/Icon/Icon.stories.tsx
  src/components/common/Icon/Icon.types.ts
  src/components/common/Icon/index.tsx
  src/styles/global.ts
  src/svg.d.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat

#36 [FEAT] Progress 컴포넌트, 스토리북
  src/components/common/Progress/Progress.stories.tsx
  src/components/common/Progress/Progress.styled.ts
  src/components/common/Progress/Progress.types.ts
  src/components/common/Progress/index.tsx
Labels: feat

#38 [FEAT] Button 컴포넌트 css 수정
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/Button.styled.ts
  src/components/common/Button/Button.types.ts
Labels: feat

#40 [FEAT] IconButton 컴포넌트, 스토리북
  src/components/common/IconButton/IconButton.stories.tsx
  src/components/common/IconButton/IconButton.styled.ts
  src/components/common/IconButton/IconButton.types.ts
  src/components/common/IconButton/index.tsx
Labels: feat

#46 [FEAT] 째깍 아이콘 추가
  src/assets/icons/anonymous.svg
  src/assets/icons/index.tsx
  src/assets/icons/jjakkak-1.svg
  src/assets/icons/jjakkak-10.svg
  src/assets/icons/jjakkak-2.svg
  src/assets/icons/jjakkak-3.svg
  src/assets/icons/jjakkak-4.svg
  src/assets/icons/jjakkak-5.svg
  src/assets/icons/jjakkak-6.svg
  src/assets/icons/jjakkak-7.svg
  src/assets/icons/jjakkak-8.svg
  src/assets/icons/jjakkak-9.svg
  src/assets/icons/jjakkak-fill-1.svg
  src/assets/icons/jjakkak-fill-10.svg
  src/assets/icons/jjakkak-fill-2.svg
  src/assets/icons/jjakkak-fill-3.svg
  src/assets/icons/jjakkak-fill-4.svg
  src/assets/icons/jjakkak-fill-5.svg
  src/assets/icons/jjakkak-fill-6.svg
  src/assets/icons/jjakkak-fill-7.svg
  src/assets/icons/jjakkak-fill-8.svg
  src/assets/icons/jjakkak-fill-9.svg
  src/assets/icons/jjakkak-gray-3.svg
  src/assets/icons/jjakkak-illust.svg
  src/assets/icons/jjakkaks-illust.svg
Labels: feat

#52 [FEAT] size 프롭에 width, height 레코드 타입 추가
  src/components/common/Icon/Icon.stories.tsx
  src/components/common/Icon/Icon.types.ts
  src/components/common/Icon/index.tsx
Labels: feat

#53 [FEAT] Chip 디자인 반영
  src/components/common/Chip/Chip.stories.tsx
  src/components/common/Chip/Chip.styled.ts
  src/components/common/Chip/Chip.types.ts
Labels: feat

#45 [FEAT] Slider 컴포넌트, 스토리북
  src/components/common/Slider/Slider.stories.tsx
  src/components/common/Slider/Slider.styled.ts
  src/components/common/Slider/Slider.types.ts
  src/components/common/Slider/index.tsx
Labels: feat

#60 [FEAT] App layout
  src/App.tsx
  src/components/common/AppLayout/AppLayout.styled.ts
  src/components/common/AppLayout/AppLayout.types.ts
  src/components/common/AppLayout/index.tsx
Labels: feat

#58 [FEAT] Button 컴포넌트 cursor 지정
  src/components/common/Button/Button.styled.ts
Labels: feat

#63 [FEAT] 째깍 로고 추가
  src/assets/icons/index.tsx
  src/assets/icons/jjakkak-circle-1.svg
  src/assets/icons/jjakkak-circle-2.svg
  src/assets/icons/jjakkak-text.svg
Labels: feat

#47 [FEAT] FixedBottomButton 컴포넌트, 스토리북
  src/components/common/FixedBottomButton/FixedBottomButton.stories.tsx
  src/components/common/FixedBottomButton/FixedBottomButton.styled.ts
  src/components/common/FixedBottomButton/FixedBottomButton.types.ts
  src/components/common/FixedBottomButton/index.tsx
Labels: feat

#44 [FEAT] Typography 변경된 디자인 반영
  src/components/common/Typography/Typography.mdx
  src/components/common/Typography/Typography.styled.ts
  src/components/common/Typography/index.tsx
Labels: feat

#69 [FEAT] FlexBox 컴포넌트에 프롭 추가
  src/components/common/Button/Button.stories.tsx
  src/components/common/Chip/Chip.stories.tsx
  src/components/common/FixedBottomButton/FixedBottomButton.stories.tsx
  src/components/common/FixedBottomButton/index.tsx
  src/components/common/FlexBox/FlexBox.stories.tsx
  src/components/common/FlexBox/FlexBox.styled.ts
  src/components/common/FlexBox/FlexBox.types.ts
  src/components/common/FlexBox/index.tsx
  src/components/common/IconButton/IconButton.stories.tsx
Labels: feat

#64 [FEAT] Header 컴포넌트, 스토리북
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/Header.types.ts
  src/components/common/Header/index.tsx
Labels: feat

#67 [FEAT] KaKao Login 페이지 UI 작업
  public/icons/kakao_login.png
  src/App.tsx
  src/assets/icons/index.tsx
  src/main.tsx
  src/pages/Login.tsx
Labels: feat

#72 [FEAT] KakaoLoginButton 컴포넌트, 스토리북 작성
  src/assets/icons/index.tsx
  src/assets/icons/kakaotalk-1.svg
  src/assets/icons/kakaotalk-2.svg
  src/components/features/KakaoLoginButton/KakaoLoginButton.stories.tsx
  src/components/features/KakaoLoginButton/KakaoLoginButton.styled.ts
  src/components/features/KakaoLoginButton/index.tsx
  src/constants/auth.ts
  src/lib/env.ts
Labels: feat

#79 [BUGFIX] 헤더에서 변경된 네이밍 사용 중인 부분 수정
  src/components/common/Header/Header.stories.tsx
Labels: fix

#87 [CHORE] 버그픽스 PR 생성 시 fix 라벨 지정
  .github/labeler-config.yaml
Labels: chore

#56 [FEAT] Calendar 컴포넌트, 스토리북
  src/components/common/Calendar/Calendar.stories.tsx
  src/components/common/Calendar/Calendar.styled.ts
  src/components/common/Calendar/Calendar.types.ts
  src/components/common/Calendar/index.tsx
  src/components/common/Calendar/useCalendar.tsx
  src/constants/calendar.ts
Labels: feat

#91 [BUGFIX] TextField x 버튼 밀림 방지
  src/assets/icons/delete-rounded.svg
  src/assets/icons/index.tsx
  src/components/common/IconButton/IconButton.types.ts
  src/components/common/IconButton/index.tsx
  src/components/common/TextField/TextField.styled.ts
  src/components/common/TextField/index.tsx
Labels: fix

#49 [FEAT] 카드형 Switch 컴포넌트, 스토리북
  public/images/btn-anonymous.svg
  public/images/btn-jjakkak-3.svg
  src/assets/icons/anonymous.svg
  src/assets/icons/index.tsx
  src/assets/icons/jjakkak-gray-3.svg
  src/components/common/Switch/Switch.stories.tsx
  src/components/common/Switch/Switch.styled.ts
  src/components/common/Switch/Switch.types.ts
  src/components/common/Switch/index.tsx
Labels: feat

#92 [FEAT] Member 컴포넌트, 스토리북
  src/assets/icons/check.svg
  src/assets/icons/circle-1.svg
  src/assets/icons/circle-2.svg
  src/assets/icons/index.tsx
  src/assets/icons/jjakkak-1.svg
  src/assets/icons/jjakkak-10.svg
  src/assets/icons/jjakkak-2.svg
  src/assets/icons/jjakkak-3.svg
  src/assets/icons/jjakkak-4.svg
  src/assets/icons/jjakkak-5.svg
  src/assets/icons/jjakkak-6.svg
  src/assets/icons/jjakkak-7.svg
  src/assets/icons/jjakkak-8.svg
  src/assets/icons/jjakkak-9.svg
  src/components/common/Member/Member.stories.tsx
  src/components/common/Member/Member.styled.ts
  src/components/common/Member/Member.types.ts
  src/components/common/Member/index.tsx
Labels: feat

#98 [FEAT] Modal 컴포넌트, 스토리북
  src/assets/icons/close.svg
  src/assets/icons/index.tsx
  src/components/common/Modal/Modal.stories.tsx
  src/components/common/Modal/Modal.styled.ts
  src/components/common/Modal/Modal.types.ts
  src/components/common/Modal/index.tsx
  src/components/common/Modal/useModal.ts
Labels: feat

#86 [FEAT] 모임 생성 페이지 UI
  src/components/common/FixedBottomButton/FixedBottomButton.stories.tsx
  src/components/common/FixedBottomButton/FixedBottomButton.styled.ts
  src/components/common/FormLayout/FormLayout.stories.tsx
  src/components/common/FormLayout/FormLayout.types.ts
  src/components/common/FormLayout/index.tsx
  src/components/common/Header/index.tsx
  src/components/features/.gitkeep
  src/components/features/CreateMeetingForm/AnonymousForm.tsx
  src/components/features/CreateMeetingForm/CategoryForm.tsx
  src/components/features/CreateMeetingForm/CreateMeetingForm.stories.tsx
  src/components/features/CreateMeetingForm/DeadlineForm.tsx
  src/components/features/CreateMeetingForm/MeetingNameForm.tsx
  src/components/features/CreateMeetingForm/MemberForm.tsx
  src/components/features/CreateMeetingForm/PeriodForm.tsx
  src/components/features/CreateMeetingForm/index.ts
  src/components/features/CreateMeetingForm/types.ts
  src/constants/meetingForm.ts
  src/contexts/FunnelProgressContext.tsx
  src/hooks/.gitkeep
  src/hooks/useFunnel.tsx
  src/hooks/useFunnelProgressContext.tsx
  src/pages/.gitkeep
  src/pages/NewMeeting.tsx
  src/routes/route.tsx
Labels: feat

#108 [FEAT] Chip에 value 프롭 추가
  src/components/common/Chip/Chip.stories.tsx
  src/components/common/Chip/Chip.styled.ts
  src/components/common/Chip/Chip.types.ts
  src/components/common/Chip/index.tsx
Labels: feat

#116 [CHORE] /src/components에 변경사항이 생긴 경우에만 스토리북 배포
  .github/workflows/check-pull-request.yaml
  .github/workflows/deploy-storybook.yaml
  .github/workflows/deploy.yaml
  .github/workflows/prepublish-storybook.yaml
Labels: chore
